### ISSUE TITLE
Support for link rel="icon" and .png icons

### ISSUE THREAD

**Issue by jeantoulza** [keeweb/favicon-proxy#1]
Hello,

I noticed Keeweb is using this service to download favicons. However it does not download all favicons.

For example: GET https://favicon-antelle.rhcloud.com/www.dailymotion.com
Expected result: the server sends the favicon of dailymotion.com
Actual result: server sends a 404 status

https://www.google.com/s2/favicons?domain=www.dailymotion.com works well.

Two possible fixes could be:
- get PNG icon if ICO is not found
- if PNG icon is not found, follow http redirections (like Location header and meta http-equiv="REFRESH") until no other redirection, then follow link rel="icon" if provided

**Comment by antelle** [comment]
https://favicon.keeweb.info/www.dailymotion.com
