### ISSUE TITLE
gmail.com favicon

### ISSUE THREAD

**Issue by maximzasorin** [keeweb/favicon-proxy#2]
Request: https://favicon.keeweb.info/gmail.com returns "No favicon", should return favicon for mail.google.com: https://favicon.keeweb.info/mail.google.com

**Comment by antelle** [comment]
Hi! 
It's because of weird redirects, this is what happens when you load gmail.com:
```
GET http://gmail.com => 301 https://gmail.com
GET https://gmail.com => 302 https://www.google.com/gmail/
GET https://www.google.com/gmail/ => 302 https://mail.google.com/mail/
=== we stop here, after three requests ===
GET https://mail.google.com/mail/ => 302 https://accounts.google.com/ServiceLogin?service=mail
```

**Comment by antelle** [comment]
I just tried to increase it to 5 and it didn't help: it downloads a page without a favicon :( 
This page has a javascript redirect inside, unfortunately we cannot follow them.

**Comment by antelle** [comment]
I've added a weird hack for gmail: https://github.com/keeweb/favicon-proxy/commit/2884feefaef3833cfafdb9bee265b42d1c92763b, only because gmail is popular.
Now it's working: https://favicon.keeweb.info/gmail.com
