### ISSUE TITLE
Doesn't work when "type" attribute is after "href"

### ISSUE THREAD

**Issue by SamuelMoraesF** [keeweb/favicon-proxy#3]
Favicon can't be detected in the following case:

`<link href='/template/new/images/favicon.ico' rel='icon' type='image/x-icon' />`

**Comment by antelle** [comment]
Fixed, thanks! Could you please confirm if it's working for you now?

**Comment by SamuelMoraesF** [comment]
Not yet: `https://favicon.keeweb.info/2captcha.com`

**Comment by antelle** [comment]
Thanks, fixed
