### ISSUE TITLE
Some domains don't return anything

### ISSUE THREAD

**Issue by immanuelfodor** [keeweb/favicon-proxy#6]
Hi, this project is awesome, however, there are some domains that doesn't seem to return anything as favicon even though they have one. 

Example: https://services.keeweb.info/favicon/resources.infosecinstitute.com

How is this possible? :)

**Comment by antelle** [comment]
Hi! It's because their `favicon.ico` returns 200 but it's broken: https://resources.infosecinstitute.com/favicon.ico

**Comment by antelle** [comment]
Tip: if you run `DEBUG_FAVICON=1 node index.js`, you will see some debug output.

**Comment by immanuelfodor** [comment]
Hmm, I see, it's indeed broken. However, they have several other icons that Chrome can interpret and display: 

```html
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="manifest" href="/favicons/site.webmanifest">
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#00334a">
```

Could one of these be returned instead of the broken favicon in such case? Is there a way to somehow detect this anomaly? Based on favicon.ico size, etc.

**Comment by antelle** [comment]
It's possible, however we need to load the website first. Now we try load a favicon, and if it works, which happens in most of cases, this icon is returned. Otherwise we use the website.
Perhaps it should be a configuration option, what to load first.
