### ISSUE TITLE
Configure throttling thresholds from env

### ISSUE THREAD

**Issue by immanuelfodor** [keeweb/favicon-proxy#7]
The recent addition of throttling makes a self-hosted instance block trusted sources, so I needed to manually edit the file to override the settings: 
- `IP_THROTTLING_MS = 0;`
- `IP_THROTTLING_AGGRESSIVE_LOCKDOWN_DETECTION_THRESHOLD = 0;`

Please make these configurable from env. The defaults can be your current values if the env values are empty.

**Comment by antelle** [comment]
Hi! Added variables:
- `IP_THROTTLING_MS`
- `IP_THROTTLING_AGGRESSIVE_LOCKDOWN_DETECTION_THRESHOLD`
- `IP_THROTTLING_AGGRESSIVE_LOCKDOWN_TIME_MS`

**Comment by immanuelfodor** [comment]
Thank you, works flawlessly!
